### ISSUE TITLE
Add me to the spanish team!!

### ISSUE THREAD

**Issue by roxerto** [thejsway/thejsway_es#1]
there is anybody already doing the Spanish translation? I would like to join the team! I don't know nothing about markdowns yet, but I think I can just download and edit the raw files available here on Github!

**Comment by bpesquet** [comment]
Any help would be much appreciated!
I just sent you an invitation to the spanish team. Feel free to ask questions regarding the translation setup.

**Comment by roxerto** [comment]
Hi buddy, I just finished translating the first chapter; I'm new into
GitHub, should I upload the .MD file?.

For the translation I used the original raw .MD files as a template, and  I
only replaced the English text with the Spanish translation.

Do you have any guidelines for the translation? I think a short text or
paragraph at the beginning of the book (in the Spanish version and maybe
another translations) about the fact that English is the native language of
JavaScript, just to warn readers they'll see "string", when they ask
typeof(), and not "cadena" (Spanish word for "string"). Maybe it's obvious
but it is worth. Or peut-être a table with English Spanish equivalencies. I
don't know, just some ideas!

Greetings from Mexico!

**Comment by bpesquet** [comment]
Hi,

Thanks a lot for this work! The standard process is as follows:

1. clone the [thejsway_es](https://github.com/thejsway/thejsway_es) repo. This will create a `thejsway_en` folder on your local machine
1. Copy your `.md` files in the `manuscript` subdirectory of this folder
1. Commit and push, so that the [thejsway_es](https://github.com/thejsway/thejsway_es) repo is synchronized with your local version
1. There is no step 4 ;)

Maybe you should read [this guide](https://guides.github.com/introduction/git-handbook/) if you are brand new to working with Git and GitHub. 

**A simpler solution**: alternatively, you can simply upload your `.md` files into the `manuscript` subdirectory of the  [thejsway_es](https://github.com/thejsway/thejsway_es) repo.

Keep up the good work and thanks again!

**Comment by roxerto** [comment]
I just uploaded the three first chapters I translated, can you please copy
the images folder to my Spanish folder? so every chapter shows the linked
pictures.

**Comment by bpesquet** [comment]
Thanks for your work!

I uploaded the images folder as requested. However, output doesn't match your Spanish text messages in code. It's a difficult problem, either you switch back to English for string values or one has to re-do all the screen captures in Spanish.

I let you choose what seems best to you.

**Comment by roxerto** [comment]
First I'll finish translating all the chapters and then I think I'll make
the screenshots match the translation!

Au revoir !
